# Customer Revenue Analytics & Behavioral Segmentation

## Stage 1 — Transaction Analysis and Customer Feature Engineering

### Objective

Analyze historical e-commerce transaction data to understand customer purchasing behavior, revenue generation, basket characteristics, and return behavior.

### Key Tasks

- Load and inspect the transaction data
- Clean and validate transaction records
- Calculate transaction-level revenue
- Aggregate transactions into customer-level features
- Analyze purchase frequency, revenue, recency, basket value, and product behavior
- Analyze customer return behavior
- Create behavioral customer segments

## Loading the necessary libraries

## 1. Data Loading and Initial Inspection

Load the historical e-commerce transaction data and inspect its structure, dimensions, columns, data types, and basic statistics.

## 2. Data Cleaning and Validation

Check for:
- Missing values
- Duplicate records
- Invalid quantities
- Invalid prices
- Transaction consistency

Clean the data before performing customer-level analysis.

## 3. Transaction-Level Revenue Analysis

Calculate the monetary value of each transaction line and analyze purchase and return transactions separately.

## 4. Customer-Level Feature Engineering

Aggregate transaction-level information by `UserID` to create customer-level behavioral features, including:

- Purchase frequency
- Gross revenue
- Unique products
- Average basket value
- Recency
- Return events
- Return value
- Return value rate

## 5. Customer Behavioral Analysis

Analyze customer purchasing patterns, revenue contribution, basket behavior, and return behavior.

## 6. Behavioral Customer Segmentation

Use the engineered customer-level features to classify customers into behavioral segments that can later support customer targeting.

In [1]:
import pandas as pd
import numpy as np

## Predefining the Path Variable

In [2]:
customer_transaction_path="../Data/Customers_Transactions.xlsx"

## checking the how many sheets inside the customer transaction datasets

In [3]:
sheets=pd.ExcelFile(customer_transaction_path)
sheets.sheet_names

['Year 2019-2020', 'Year 2020-2021']

## Exploring the Datasets wht we have

In [4]:
df1=pd.read_excel(customer_transaction_path)
df1.head()

,EventID,EventType,ProductID,ProductName,Quantity,EventDateTime,UnitPrice,UserID
0,612890,Purchased,97393,DIWALI LANTERN WITH CARDBOARD,32,2019-12-01 07:45:00,624.80,25430
1,612890,Purchased,91668P,FLOWER POTS WITH FLOWER,32,2019-12-01 07:45:00,607.40,25430
2,612890,Purchased,91668W,RED COLORED LIGHTS,32,2019-12-01 07:45:00,607.40,25430
3,612890,Purchased,34386,PHOTO FRAME,68,2019-12-01 07:45:00,197.85,25430
4,612890,Purchased,33577,FUNNY HAT,44,2019-12-01 07:45:00,123.90,25430

# checking the column names and any null values is present or not

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417534 entries, 0 to 417533
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EventID        417534 non-null  object
 1   EventType      417534 non-null  object
 2   ProductID      417534 non-null  object
 3   ProductName    417534 non-null  object
 4   Quantity       417534 non-null  int64
 5   EventDateTime  417534 non-null  datetime64[ns]
 6   UnitPrice      417534 non-null  float64
 7   UserID         417534 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 25.5+ MB

## Loading the 2nd sheet in the excel file

In [6]:
df2=pd.read_excel(customer_transaction_path,sheet_name=sheets.sheet_names[1])
df2.head()

,EventID,EventType,ProductID,ProductName,Quantity,EventDateTime,UnitPrice,UserID
0,659821,Purchased,97468A,ROSE GOLD VANITY MIRROR,16,2020-12-01 08:26:00,237.00,30195
1,659821,Purchased,83398,,16,2020-12-01 08:26:00,310.08,30195
2,659821,Purchased,96751B,WOODEN SERVING TRAY SET,18,2020-12-01 08:26:00,254.40,30195
3,659821,Purchased,96374G,LEATHER PASSPORT HOLDER,16,2020-12-01 08:26:00,310.08,30195
4,659821,Purchased,96374E,PASTEL COTTON CANDY CANDLE,16,2020-12-01 08:26:00,310.08,30195

## Merging the two dataframes and combining them into one

In [7]:
df=pd.concat([df1,df2])
df.head()

,EventID,EventType,ProductID,ProductName,Quantity,EventDateTime,UnitPrice,UserID
0,612890,Purchased,97393,DIWALI LANTERN WITH CARDBOARD,32,2019-12-01 07:45:00,624.80,25430
1,612890,Purchased,91668P,FLOWER POTS WITH FLOWER,32,2019-12-01 07:45:00,607.40,25430
2,612890,Purchased,91668W,RED COLORED LIGHTS,32,2019-12-01 07:45:00,607.40,25430
3,612890,Purchased,34386,PHOTO FRAME,68,2019-12-01 07:45:00,197.85,25430
4,612890,Purchased,33577,FUNNY HAT,44,2019-12-01 07:45:00,123.90,25430

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 740589 entries, 0 to 323054
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EventID        740589 non-null  object
 1   EventType      740589 non-null  object
 2   ProductID      740589 non-null  object
 3   ProductName    740589 non-null  object
 4   Quantity       740589 non-null  int64
 5   EventDateTime  740589 non-null  datetime64[ns]
 6   UnitPrice      740589 non-null  float64
 7   UserID         740589 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 50.9+ MB

In [9]:
df[(df["EventType"]=="Purchased") & (df["Quantity"] < 0)]

Empty DataFrame
Columns: [EventID, EventType, ProductID, ProductName, Quantity, EventDateTime, UnitPrice, UserID]
Index: []

In [10]:
df.head(15)

,EventID,EventType,ProductID,ProductName,Quantity,EventDateTime,UnitPrice,UserID
0,612890,Purchased,97393,DIWALI LANTERN WITH CARDBOARD,32,2019-12-01 07:45:00,624.80,25430
1,612890,Purchased,91668P,FLOWER POTS WITH FLOWER,32,2019-12-01 07:45:00,607.40,25430
2,612890,Purchased,91668W,RED COLORED LIGHTS,32,2019-12-01 07:45:00,607.40,25430
3,612890,Purchased,34386,PHOTO FRAME,68,2019-12-01 07:45:00,197.85,25430
4,612890,Purchased,33577,FUNNY HAT,44,2019-12-01 07:45:00,123.90,25430
5,612890,Purchased,34409,CAT FOOD BOWL,44,2019-12-01 07:45:00,158.70,25430
6,612890,Purchased,34216,MOBILE CASE,44,2019-12-01 07:45:00,123.90,25430
7,612890,Purchased,33868,FACE MASK,30,2019-12-01 07:45:00,537.80,25430
8,612891,Purchased,34695,HOLI COLORS,32,2019-12-01 07:46:00,237.00,25430
9,612891,Purchased,34694,WOODEN PLATES,32,2019-12-01 07:46:00,341.40,25430
10,612891,Purchased,34540,FIRST AID BOX,44,2019-12-01 07:46:00,158.70,25430
11,612891,Purchased,34698,BOOKS,32,2019-12-01 07:46:00,237.00,25430
12,612892,Purchased,60518C,LAPTOP SCREEN PROTECTOR,30,2019-12-01 09:06:00,537.80,25423
13,612892,Purchased,34100,WIRELESS MOUSE,38,2019-12-01 09:06:00,489.30,25423
14,612892,Purchased,34099,WATER BOTTLE,13,2019-12-01 09:06:00,537.80,25423

In [11]:
print("Columns:")
print(df.columns.to_list())

print("Shape")
print(df.shape)

print("Data Types:")
print(df.dtypes)

print("Event type values")
print(df["EventType"].value_counts())

Columns:
['EventID', 'EventType', 'ProductID', 'ProductName', 'Quantity', 'EventDateTime', 'UnitPrice', 'UserID']
Shape
(740589, 8)
Data Types:
EventID                  object
EventType                object
ProductID                object
ProductName              object
Quantity                  int64
EventDateTime    datetime64[ns]
UnitPrice               float64
UserID                    int64
dtype: object
Event type values
EventType
Purchased    723488
Returned      17101
Name: count, dtype: int64

In [12]:
# How many unique EventIDs and Users are present?
print("Unique EventIDs:", df["EventID"].nunique())
print("Unique Users:", df["UserID"].nunique())
print("Unique Products:", df["ProductID"].nunique())

# How many rows does each EventID typically contain?
event_rows = df.groupby("EventID").size()

print("\nRows per EventID:")
print(event_rows)

# Show events that contain more than one row
print("\nExample EventIDs with multiple rows:")
print(event_rows[event_rows > 1].head(10))

Unique EventIDs: 40553
Unique Users: 5798
Unique Products: 4644

Rows per EventID:
EventID
612890      8
612891      4
612892     19
612893     23
612894     17
           ..
R704940     1
R704946     2
R704955     1
R705024     1
R705025     2
Length: 40553, dtype: int64

Example EventIDs with multiple rows:
EventID
612890     8
612891     4
612892    19
612893    23
612894    17
612895    19
612896     2
612897     4
612898    23
612899     7
dtype: int64

In [13]:
# Check how many unique values each EventID has for key columns

event_consistency = df.groupby("EventID").agg(
    unique_users=("UserID", "nunique"),
    unique_event_types=("EventType", "nunique"),
    unique_dates=("EventDateTime", "nunique"),
    number_of_rows=("EventID", "size")
)

print(event_consistency.describe())

       unique_users  unique_event_types  unique_dates  number_of_rows
count       40553.0             40553.0  40553.000000    40553.000000
mean            1.0                 1.0      1.001430       18.262249
std             0.0                 0.0      0.037792       23.028297
min             1.0                 1.0      1.000000        1.000000
25%             1.0                 1.0      1.000000        3.000000
50%             1.0                 1.0      1.000000       12.000000
75%             1.0                 1.0      1.000000       24.000000
max             1.0                 1.0      2.000000      542.000000

In [14]:
# Remove only exact duplicate rows
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Rows after removing exact duplicates:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))
print("Remaining exact duplicates:",
      df_clean.duplicated().sum())

Original rows: 740589
Rows after removing exact duplicates: 718203
Rows removed: 22386
Remaining exact duplicates: 0

In [15]:
# Check quantity patterns by event type

quantity_check = df_clean.groupby("EventType")["Quantity"].agg(
    ["count", "min", "max", "mean"]
)

print(quantity_check)

print("\nQuantity <= 0 by EventType:")

print(
    df_clean[df_clean["Quantity"] <= 0]
    ["EventType"]
    .value_counts()
)

            count    min    max       mean
EventType
Purchased  701377     11  81015  27.270716
Returned    16826 -80985      9 -16.736895

Quantity <= 0 by EventType:
EventType
Returned    3212
Name: count, dtype: int64

In [16]:
df_clean["LineValue"]=df_clean["UnitPrice"] * df_clean["Quantity"]
df_clean.head()

,EventID,EventType,ProductID,ProductName,Quantity,EventDateTime,UnitPrice,UserID,LineValue
0,612890,Purchased,97393,DIWALI LANTERN WITH CARDBOARD,32,2019-12-01 07:45:00,624.80,25430,19993.6
1,612890,Purchased,91668P,FLOWER POTS WITH FLOWER,32,2019-12-01 07:45:00,607.40,25430,19436.8
2,612890,Purchased,91668W,RED COLORED LIGHTS,32,2019-12-01 07:45:00,607.40,25430,19436.8
3,612890,Purchased,34386,PHOTO FRAME,68,2019-12-01 07:45:00,197.85,25430,13453.8
4,612890,Purchased,33577,FUNNY HAT,44,2019-12-01 07:45:00,123.90,25430,5451.6

In [17]:
# Inspect quantity and LineValue signs for returned events

returned = df_clean[df_clean["EventType"] == "Returned"]

print("Returned rows with negative quantity:",
      (returned["Quantity"] < 0).sum())

print("Returned rows with positive quantity:",
      (returned["Quantity"] > 0).sum())

print("Returned rows with zero quantity:",
      (returned["Quantity"] == 0).sum())

print("\nLineValue sign:")
print(
    returned["LineValue"]
    .apply(lambda x: "Negative" if x < 0 else "Positive" if x > 0 else "Zero")
    .value_counts()
)

Returned rows with negative quantity: 2961
Returned rows with positive quantity: 13614
Returned rows with zero quantity: 251

LineValue sign:
LineValue
Positive    13614
Negative     2961
Zero          251
Name: count, dtype: int64

In [18]:
gross_revenue = df_clean.loc[
    df_clean["EventType"] == "Purchased",
    "LineValue"
].sum()
return_value = df_clean.loc[
    df_clean["EventType"] == "Returned",
    "LineValue"
].abs().sum()

print(gross_revenue,return_value)

3987728961.5400023 364755375.14000005

In [19]:
# Core revenue metrics

net_revenue = gross_revenue - return_value

return_value_rate = return_value / gross_revenue

print(f"Gross Revenue:       {gross_revenue:,.2f}")
print(f"Return Value:        {return_value:,.2f}")
print(f"Net Revenue:         {net_revenue:,.2f}")
print(f"Return Value Rate:   {return_value_rate:.2%}")

Gross Revenue:       3,987,728,961.54
Return Value:        364,755,375.14
Net Revenue:         3,622,973,586.40
Return Value Rate:   9.15%

# Creating the Transaction level dataset

In [20]:
# Create transaction-level dataset

transaction_df = (
    df_clean
    .groupby("EventID")
    .agg(
        UserID=("UserID", "first"),
        EventType=("EventType", "first"),
        TransactionDate=("EventDateTime", "min"),
        NumberOfLines=("ProductID", "size"),
        UniqueProducts=("ProductID", "nunique"),
        TotalQuantity=("Quantity", "sum"),
        TransactionValue=("LineValue", "sum")
    )
    .reset_index()
)

transaction_df.head()

,EventID,UserID,EventType,TransactionDate,NumberOfLines,UniqueProducts,TotalQuantity,TransactionValue
0,612890,25430,Purchased,2019-12-01 07:45:00,8,8,326,106341.00
1,612891,25430,Purchased,2019-12-01 07:46:00,4,4,140,33075.60
2,612892,25423,Purchased,2019-12-01 09:06:00,19,19,493,154245.36
3,612893,27707,Purchased,2019-12-01 09:08:00,23,23,445,112372.00
4,612894,30447,Purchased,2019-12-01 09:24:00,17,17,1166,294014.78

In [21]:
print("Number of transactions:", transaction_df["EventID"].nunique())
print("Number of transaction rows:", len(transaction_df))
print("Number of users:", transaction_df["UserID"].nunique())

Number of transactions: 40553
Number of transaction rows: 40553
Number of users: 5798

In [22]:
# Number of purchase transactions per customer

purchase_frequency = (
    transaction_df[transaction_df["EventType"] == "Purchased"]
    .groupby("UserID")
    .size()
    .rename("PurchaseFrequency")
    .reset_index()
)

purchase_frequency.head()

   UserID  PurchaseFrequency
0   24691                 12
1   24692                  7
2   24693                  5
3   24694                  3
4   24695                  1

In [23]:
purchase_frequency["PurchaseFrequency"].describe()

count    5726.000000
mean        5.823612
std        11.867815
min         1.000000
25%         1.000000
50%         3.000000
75%         6.000000
max       357.000000
Name: PurchaseFrequency, dtype: float64

## Gross Revenue per user

In [24]:
# Gross revenue generated by each customer from purchase transactions

customer_gross_revenue = (
    transaction_df[transaction_df["EventType"] == "Purchased"]
    .groupby("UserID")["TransactionValue"]
    .sum()
    .rename("GrossRevenue")
    .reset_index()
)

customer_gross_revenue.head()

   UserID  GrossRevenue
0   24691    8064806.57
1   24692    1030189.14
2   24693     427669.40
3   24694    1102907.53
4   24695     113235.85

In [25]:
customer_gross_revenue["GrossRevenue"].describe()

count    5.726000e+03
mean     6.964249e+05
std      2.226848e+06
min      2.272500e+02
25%      1.077541e+05
50%      2.597367e+05
75%      6.548118e+05
max      7.899182e+07
Name: GrossRevenue, dtype: float64

In [26]:
# Sort customers by gross revenue from highest to lowest

revenue_sorted = customer_gross_revenue.sort_values(
    "GrossRevenue",
    ascending=False
).reset_index(drop=True)

# Top 10% of purchasing customers
top_10_count = int(np.ceil(len(revenue_sorted) * 0.10))

top_10_revenue = revenue_sorted.head(top_10_count)["GrossRevenue"].sum()

total_customer_revenue = revenue_sorted["GrossRevenue"].sum()

top_10_share = top_10_revenue / total_customer_revenue

print("Number of purchasing customers:", len(revenue_sorted))
print("Top 10% customer count:", top_10_count)
print(f"Top 10% gross revenue: {top_10_revenue:,.2f}")
print(f"Total gross revenue: {total_customer_revenue:,.2f}")
print(f"Top 10% revenue share: {top_10_share:.2%}")

Number of purchasing customers: 5726
Top 10% customer count: 573
Top 10% gross revenue: 2,237,830,712.27
Total gross revenue: 3,987,728,961.54
Top 10% revenue share: 56.12%

In [27]:
# Purchase transaction basket value distribution

purchase_transactions = transaction_df[
    transaction_df["EventType"] == "Purchased"
].copy()

basket_value = purchase_transactions["TransactionValue"]

print(basket_value.describe())

count    3.334600e+04
mean     1.195864e+05
std      2.173950e+05
min      1.666500e+02
25%      4.942346e+04
50%      8.681965e+04
75%      1.397898e+05
max      1.588785e+07
Name: TransactionValue, dtype: float64

In [28]:
print(f"Mean basket value:   {basket_value.mean():,.2f}")
print(f"Median basket value: {basket_value.median():,.2f}")
print(f"Minimum:             {basket_value.min():,.2f}")
print(f"Maximum:             {basket_value.max():,.2f}")

Mean basket value:   119,586.43
Median basket value: 86,819.65
Minimum:             166.65
Maximum:             15,887,851.65

In [29]:
print(basket_value.quantile([0.90, 0.95, 0.99, 0.995, 0.999]))

0.900    2.258807e+05
0.950    2.981815e+05
0.990    5.900495e+05
0.995    8.856317e+05
0.999    2.416199e+06
Name: TransactionValue, dtype: float64

In [30]:
# Average basket value per purchasing customer

customer_avg_basket = (
    purchase_transactions
    .groupby("UserID")["TransactionValue"]
    .mean()
    .rename("AverageBasketValue")
    .reset_index()
)

print(customer_avg_basket["AverageBasketValue"].describe())

count    5.726000e+03
mean     1.131849e+05
std      2.235315e+05
min      2.272500e+02
25%      5.819148e+04
50%      8.953616e+04
75%      1.285438e+05
max      1.048272e+07
Name: AverageBasketValue, dtype: float64

## Exploring the Returned Events

In [31]:
# Number of return events per customer

customer_return_events = (
    transaction_df[transaction_df["EventType"] == "Returned"]
    .groupby("UserID")
    .size()
    .rename("ReturnEvents")
    .reset_index()
)

customer_return_events["ReturnEvents"].describe()

count    2468.000000
mean        2.920178
std         4.656384
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max       103.000000
Name: ReturnEvents, dtype: float64

In [32]:
customer_df = (
    purchase_frequency
    .merge(customer_gross_revenue, on="UserID", how="outer")
    .merge(customer_avg_basket, on="UserID", how="outer")
    .merge(customer_return_events, on="UserID", how="outer")
)

customer_df["ReturnEvents"] = customer_df["ReturnEvents"].fillna(0)

customer_df.head()

   UserID  PurchaseFrequency  GrossRevenue  AverageBasketValue  ReturnEvents
0   24691               12.0    8064806.57       672067.214167           5.0
1   24692                7.0    1030189.14       147169.877143           0.0
2   24693                5.0     427669.40        85533.880000           0.0
3   24694                3.0    1102907.53       367635.843333           1.0
4   24695                1.0     113235.85       113235.850000           0.0

In [33]:
print("Customer rows:", len(customer_df))
print("Unique customers:", customer_df["UserID"].nunique())
print(customer_df.isna().sum())

Customer rows: 5798
Unique customers: 5798
UserID                 0
PurchaseFrequency     72
GrossRevenue          72
AverageBasketValue    72
ReturnEvents           0
dtype: int64

In [34]:
return_only_customers = customer_df[
    customer_df["PurchaseFrequency"].isna()
].copy()

print("Customers with returns but no recorded purchases:",
      len(return_only_customers))

print("\nReturn events for these customers:")
print(return_only_customers["ReturnEvents"].describe())

Customers with returns but no recorded purchases: 72

Return events for these customers:
count    72.000000
mean      1.069444
std       0.255992
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       2.000000
Name: ReturnEvents, dtype: float64

In [35]:
customer_df["ReturnEventRate"] = np.where(
    customer_df["PurchaseFrequency"] > 0,
    customer_df["ReturnEvents"] / customer_df["PurchaseFrequency"],
    np.nan
)

print(customer_df["ReturnEventRate"].describe())

count    5726.000000
mean        0.198152
std         0.354040
min         0.000000
25%         0.000000
50%         0.000000
75%         0.285714
max         5.000000
Name: ReturnEventRate, dtype: float64

In [36]:
transaction_df.head()

,EventID,UserID,EventType,TransactionDate,NumberOfLines,UniqueProducts,TotalQuantity,TransactionValue
0,612890,25430,Purchased,2019-12-01 07:45:00,8,8,326,106341.00
1,612891,25430,Purchased,2019-12-01 07:46:00,4,4,140,33075.60
2,612892,25423,Purchased,2019-12-01 09:06:00,19,19,493,154245.36
3,612893,27707,Purchased,2019-12-01 09:08:00,23,23,445,112372.00
4,612894,30447,Purchased,2019-12-01 09:24:00,17,17,1166,294014.78

In [37]:
# Calculate total return value for each customer
# using the original cleaned line-level transaction data

customer_return_value = (
    df_clean[df_clean["EventType"] == "Returned"]
    .groupby("UserID")["LineValue"]
    .apply(lambda x: x.abs().sum())
    .rename("ReturnValue")
    .reset_index()
)

customer_return_value["ReturnValue"].describe()

count    2.468000e+03
mean     1.477939e+05
std      1.166039e+06
min      0.000000e+00
25%      4.638802e+03
50%      1.188855e+04
75%      3.117089e+04
max      3.053598e+07
Name: ReturnValue, dtype: float64

In [38]:
customer_df = customer_df.merge(
    customer_return_value,
    on="UserID",
    how="left"
)

customer_df["ReturnValue"] = customer_df["ReturnValue"].fillna(0)

customer_df.head()

,UserID,PurchaseFrequency,GrossRevenue,AverageBasketValue,ReturnEvents,ReturnEventRate,ReturnValue
0,24691,12.0,8064806.57,672067.214167,5.0,0.416667,8115566.6
1,24692,7.0,1030189.14,147169.877143,0.0,0.000000,0.0
2,24693,5.0,427669.40,85533.880000,0.0,0.000000,0.0
3,24694,3.0,1102907.53,367635.843333,1.0,0.333333,19636.2
4,24695,1.0,113235.85,113235.850000,0.0,0.000000,0.0

In [39]:
print("Customer rows:", len(customer_df))
print("Unique customers:", customer_df["UserID"].nunique())

print("\nMissing values:")
print(customer_df.isna().sum())

Customer rows: 5798
Unique customers: 5798

Missing values:
UserID                 0
PurchaseFrequency     72
GrossRevenue          72
AverageBasketValue    72
ReturnEvents           0
ReturnEventRate       72
ReturnValue            0
dtype: int64

In [40]:
customer_df["ReturnValueRate"] = np.where(
    customer_df["GrossRevenue"] > 0,
    customer_df["ReturnValue"] / customer_df["GrossRevenue"],
    np.nan
)

print(customer_df["ReturnValueRate"].describe())

count    5726.000000
mean        0.034215
std         0.208102
min         0.000000
25%         0.000000
50%         0.000000
75%         0.015468
max         9.232221
Name: ReturnValueRate, dtype: float64

In [41]:
print(
    "Customers with Return Value > Gross Revenue:",
    (customer_df["ReturnValueRate"] > 1).sum()
)

Customers with Return Value > Gross Revenue: 31

In [42]:
customer_df["NetRevenue"] = np.where(
    customer_df["GrossRevenue"] > 0,
    customer_df["GrossRevenue"] - customer_df["ReturnValue"],
    np.nan
)

customer_df["NetRevenue"].describe()

count    5.726000e+03
mean     6.409702e+05
std      2.029041e+06
min     -2.535639e+07
25%      1.034870e+05
50%      2.497460e+05
75%      6.351624e+05
max      6.835131e+07
Name: NetRevenue, dtype: float64

In [43]:
print("Customers with negative Net Revenue:",
      (customer_df["NetRevenue"] < 0).sum())

Customers with negative Net Revenue: 31

In [44]:
# Reference date = latest recorded purchase date

reference_date = purchase_transactions["TransactionDate"].max()

print("Reference date:", reference_date)

Reference date: 2021-12-09 12:50:00

In [45]:
# Calculate customer purchase recency in days

customer_recency = (
    purchase_transactions
    .groupby("UserID")["TransactionDate"]
    .max()
    .rename("LastPurchaseDate")
    .reset_index()
)

customer_recency["RecencyDays"] = (
    reference_date - customer_recency["LastPurchaseDate"]
).dt.days

customer_recency["RecencyDays"].describe()

count    5726.000000
mean      219.204506
std       212.706188
min         0.000000
25%        30.000000
50%       133.000000
75%       394.000000
max       739.000000
Name: RecencyDays, dtype: float64

In [48]:
customer_df = customer_df.drop(
    columns=["LastPurchaseDate_y", "RecencyDays_y"]
)

customer_df = customer_df.rename(
    columns={
        "LastPurchaseDate_x": "LastPurchaseDate",
        "RecencyDays_x": "RecencyDays"
    }
)

print(customer_df.columns.tolist())

['UserID', 'PurchaseFrequency', 'GrossRevenue', 'AverageBasketValue', 'ReturnEvents', 'ReturnEventRate', 'ReturnValue', 'ReturnValueRate', 'NetRevenue', 'LastPurchaseDate', 'RecencyDays']

In [49]:
customer_df[[
    "UserID",
    "LastPurchaseDate",
    "RecencyDays"
]].head()

   UserID    LastPurchaseDate  RecencyDays
0   24691 2021-01-18 10:01:00        325.0
1   24692 2021-12-07 15:52:00          1.0
2   24693 2021-09-25 13:13:00         74.0
3   24694 2020-10-28 08:23:00        407.0
4   24695 2021-02-02 16:01:00        309.0

## Knowing which product makes more gross revenue

In [55]:
product_revenue = (
    df_clean[df_clean["EventType"] == "Purchased"]
    .groupby("ProductID")["LineValue"]
    .sum()
    .reset_index(name="GrossRevenue")
    .sort_values("GrossRevenue", ascending=False)
    .reset_index(drop=True)
)

print("Unique products:", product_revenue["ProductID"].nunique())
print("Rows:", len(product_revenue))
print("Total gross revenue:", product_revenue["GrossRevenue"].sum())

Unique products: 4629
Rows: 4629
Total gross revenue: 3987728961.54

In [56]:
print("Unique products:", product_revenue["ProductID"].nunique())
print("Total product gross revenue:",
      product_revenue["GrossRevenue"].sum())

Unique products: 4629
Total product gross revenue: 3987728961.54

In [57]:
top_10_product_count = int(np.ceil(len(product_revenue) * 0.10))

top_10_product_revenue = (
    product_revenue
    .head(top_10_product_count)["GrossRevenue"]
    .sum()
)

total_product_revenue = product_revenue["GrossRevenue"].sum()

top_10_product_share = (
    top_10_product_revenue / total_product_revenue
)

print("Total products:", len(product_revenue))
print("Top 10% product count:", top_10_product_count)
print("Top 10% product revenue:", top_10_product_revenue)
print("Top 10% product revenue share:", f"{top_10_product_share:.2%}")

Total products: 4629
Top 10% product count: 463
Top 10% product revenue: 2411120434.83
Top 10% product revenue share: 60.46%

In [58]:
print("Product IDs in product_revenue:",
      product_revenue["ProductID"].nunique())

print("Purchased Product IDs in df:",
      df.loc[df["EventType"] == "Purchased", "ProductID"].nunique())

print("Rows in product_revenue:",
      len(product_revenue))

Product IDs in product_revenue: 4629
Purchased Product IDs in df: 4629
Rows in product_revenue: 4629

## Return Behaviour Analysis

In [59]:
return_customers = (
    customer_df[customer_df["ReturnValue"] > 0]
    [["UserID", "ReturnValue"]]
    .sort_values("ReturnValue", ascending=False)
    .reset_index(drop=True)
)

top_10_return_customers = int(
    np.ceil(len(return_customers) * 0.10)
)

top_10_return_value = (
    return_customers
    .head(top_10_return_customers)["ReturnValue"]
    .sum()
)

total_return_value = return_customers["ReturnValue"].sum()

top_10_return_share = (
    top_10_return_value / total_return_value
)

print("Customers with return value:", len(return_customers))
print("Top 10% return customers:", top_10_return_customers)
print(f"Top 10% return value: {top_10_return_value:,.2f}")
print(f"Total return value: {total_return_value:,.2f}")
print(f"Top 10% return value share: {top_10_return_share:.2%}")

Customers with return value: 2457
Top 10% return customers: 246
Top 10% return value: 327,957,541.87
Total return value: 364,755,375.14
Top 10% return value share: 89.91%

# Return Value by Customer Activity

In [60]:
return_analysis = customer_df[
    customer_df["ReturnValue"] > 0
][[
    "UserID",
    "GrossRevenue",
    "ReturnValue",
    "ReturnValueRate",
    "PurchaseFrequency",
    "RecencyDays"
]].copy()

return_analysis.describe()

,UserID,GrossRevenue,ReturnValue,ReturnValueRate,PurchaseFrequency,RecencyDays
count,2457.000000,2.385000e+03,2.457000e+03,2385.000000,2385.000000,2385.000000
mean,27530.577127,1.282148e+06,1.484556e+05,0.082146,10.010901,162.059539
std,1701.972053,3.335287e+06,1.168605e+06,0.316320,17.207353,185.936323
min,24691.000000,3.872700e+03,6.684000e+01,0.000154,1.000000,0.000000
25%,26072.000000,2.508215e+05,4.697100e+03,0.008819,3.000000,20.000000
50%,27467.000000,5.878198e+05,1.192635e+04,0.021804,6.000000,70.000000
75%,28982.000000,1.280591e+06,3.137985e+04,0.054702,11.000000,280.000000
max,30632.000000,7.899182e+07,3.053598e+07,9.232221,357.000000,739.000000

In [61]:
print(
    "Gross Revenue vs Return Value correlation:",
    return_analysis["GrossRevenue"].corr(
        return_analysis["ReturnValue"]
    )
)

Gross Revenue vs Return Value correlation: 0.4201343700176083

In [ ]:
customer_df[
    [
        "PurchaseFrequency",
        "GrossRevenue",
        "RecencyDays",
        "ReturnValueRate"
    ]
].describe(
    percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
)

       PurchaseFrequency  GrossRevenue  RecencyDays  ReturnValueRate
count        5726.000000  5.726000e+03  5726.000000      5726.000000
mean            5.823612  6.964249e+05   219.204506         0.034215
std            11.867815  2.226848e+06   212.706188         0.208102
min             1.000000  2.272500e+02     0.000000         0.000000
10%             1.000000  5.203612e+04     9.000000         0.000000
25%             1.000000  1.077541e+05    30.000000         0.000000
50%             3.000000  2.597367e+05   133.000000         0.000000
75%             6.000000  6.548118e+05   394.000000         0.015468
90%            12.000000  1.444251e+06   549.000000         0.057711
95%            19.000000  2.321028e+06   627.750000         0.112604
max           357.000000  7.899182e+07   739.000000         9.232221

In [63]:
# Thresholds based on the customer distributions we already calculated

high_value_threshold = customer_df["GrossRevenue"].quantile(0.75)

active_threshold = 90

return_risk_threshold = 0.05

print("High-value threshold:", high_value_threshold)
print("Active threshold:", active_threshold, "days")
print("Return-risk threshold:", return_risk_threshold)

High-value threshold: 654811.84
Active threshold: 90 days
Return-risk threshold: 0.05

In [64]:
def assign_segment(row):
    
    # Return risk takes priority because it represents a direct
    # revenue leakage concern.
    if row["ReturnValueRate"] >= return_risk_threshold:
        return "Return Risk"
    
    # High-value customers who are recently active
    elif (
        row["GrossRevenue"] >= high_value_threshold
        and row["RecencyDays"] <= active_threshold
    ):
        return "Protect & Grow"
    
    # High-value customers who have not purchased recently
    elif (
        row["GrossRevenue"] >= high_value_threshold
        and row["RecencyDays"] > active_threshold
    ):
        return "Win Back"
    
    # Lower-value but recently active customers
    elif row["RecencyDays"] <= active_threshold:
        return "Upsell"
    
    # Lower-value and inactive customers
    else:
        return "Monitor"


customer_df["BehavioralSegment"] = customer_df.apply(
    assign_segment,
    axis=1
)

customer_df["BehavioralSegment"].value_counts()

BehavioralSegment
Monitor           2543
Upsell            1361
Protect & Grow     941
Return Risk        644
Win Back           309
Name: count, dtype: int64

In [65]:
segment_summary = (
    customer_df
    .groupby("BehavioralSegment")
    .agg(
        CustomerCount=("UserID", "nunique"),
        GrossRevenue=("GrossRevenue", "sum"),
        ReturnValue=("ReturnValue", "sum"),
        NetRevenue=("NetRevenue", "sum")
    )
    .reset_index()
)

segment_summary["CustomerShare"] = (
    segment_summary["CustomerCount"] /
    segment_summary["CustomerCount"].sum()
)

segment_summary["GrossRevenueShare"] = (
    segment_summary["GrossRevenue"] /
    segment_summary["GrossRevenue"].sum()
)

segment_summary["ReturnValueShare"] = (
    segment_summary["ReturnValue"] /
    segment_summary["ReturnValue"].sum()
)

segment_summary["NetRevenueShare"] = (
    segment_summary["NetRevenue"] /
    segment_summary["NetRevenue"].sum()
)

segment_summary.sort_values(
    "GrossRevenue",
    ascending=False
)

,BehavioralSegment,CustomerCount,GrossRevenue,ReturnValue,NetRevenue,CustomerShare,GrossRevenueShare,ReturnValueShare,NetRevenueShare
1,Protect & Grow,941,1.926360e+09,2.677341e+07,1.899586e+09,0.162297,0.483072,0.073401,0.517571
2,Return Risk,644,8.364597e+08,2.818608e+08,5.545988e+08,0.111073,0.209758,0.772739,0.151109
0,Monitor,2543,4.589657e+08,4.987590e+07,4.563116e+08,0.438600,0.115095,0.136738,0.124329
4,Win Back,309,4.016495e+08,3.941151e+06,3.977083e+08,0.053294,0.100721,0.010805,0.108362
3,Upsell,1361,3.642946e+08,2.304082e+06,3.619905e+08,0.234736,0.091354,0.006317,0.098630

In [71]:
print("Overall Gross Revenue:",
      df_clean.loc[df_clean["EventType"] == "Purchased", "LineValue"].sum())

print("Customer Gross Revenue:",
      customer_df["GrossRevenue"].sum())

print("Difference:",
      df_clean.loc[df_clean["EventType"] == "Purchased", "LineValue"].sum()
      - customer_df["GrossRevenue"].sum())

Overall Gross Revenue: 3987728961.5400023
Customer Gross Revenue: 3987728961.54
Difference: 2.384185791015625e-06